In [1]:
# importing the libraries
import pandas as pd

In [167]:
# loading the data
df = pd.read_csv(r"C:\Users\Apex PC\Downloads\HR Employee\employee_data.csv")
df

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,TerminationType,TerminationDescription,DepartmentType,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unk,NaN,Production,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unk,NaN,Production,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unk,NaN,Sales,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unk,NaN,Sales,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unk,NaN,Sales,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,In forget fast.,Production,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unk,NaN,Production,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Smile high bar white spend forget choice near.,Production,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Fine expect election either turn.,Production,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unk,NaN,Production,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [168]:
# displaying all the columns
pd.set_option('display.max.columns', 28)

In [169]:
# renaming the columns
df.rename(columns={
    'EmpID' : 'Employee ID',
    'StartDate' : 'Start Date',
    'ExitDate' : 'Exit Date',
    'ADEmail' : 'Mail',
    'EmployeeStatus' : 'Employee Status',
    'JobFunctionDescription' : 'Job',
    'DOB' : 'Date of Birth',
    'GenderCode' : 'Gender',
    'LocationCode' : 'Zipcode',
    'MaritalDesc' : 'Marital Status', 
    'EmployeeType' : 'Job Type',
    'PayZone' : 'Zone',
    'EmployeeClassificationType' : 'Contract Type',
    'TerminationType' : 'Termination Type',
    'TerminationDescription' : 'Termination Description',
    'DepartmentType' : 'Department',
    'FirstName' : 'First Name',
    'LastName' : 'Last Name',
    'BusinessUnit' : 'Business Unit'
    }, inplace=True)

In [170]:
# joining the columns
df ['Full Name'] = df[['First Name', 'Last Name']].apply(lambda x: ' '.join(x), axis=1)
df

,Employee ID,First Name,Last Name,Start Date,Exit Date,Title,Supervisor,Mail,Business Unit,Employee Status,Job Type,Zone,Contract Type,Termination Type,Termination Description,Department,Division,Date of Birth,State,Job,Gender,Zipcode,RaceDesc,Marital Status,Performance Score,Current Employee Rating,Full Name
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unk,NaN,Production,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4,Uriah Bridges
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unk,NaN,Production,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3,Paula Small
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unk,NaN,Sales,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4,Edward Buck
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unk,NaN,Sales,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2,Michael Riordan
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unk,NaN,Sales,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3,Jasmine Onque
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,In forget fast.,Production,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3,Jakobe Erickson
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unk,NaN,Production,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3,Adyson Strickland
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Smile high bar white spend forget choice near.,Production,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2,Annabel Wilkins
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Fine expect election either turn.,Production,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2,Kendra Braun
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unk,NaN,Production,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2,Chace Kerr

In [171]:
# dropping irrelevant columns
df.drop(columns=['Termination Description', 'First Name', 'Last Name', 'Exit Date'], inplace=True)

df

,Employee ID,Start Date,Title,Supervisor,Mail,Business Unit,Employee Status,Job Type,Zone,Contract Type,Termination Type,Department,Division,Date of Birth,State,Job,Gender,Zipcode,RaceDesc,Marital Status,Performance Score,Current Employee Rating,Full Name
0,3427,20-Sep-19,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unk,Production,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4,Uriah Bridges
1,3428,11-Feb-23,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unk,Production,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3,Paula Small
2,3429,10-Dec-18,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unk,Sales,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4,Edward Buck
3,3430,21-Jun-21,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unk,Sales,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2,Michael Riordan
4,3431,29-Jun-19,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unk,Sales,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3,Jasmine Onque
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,22-Jun-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,Production,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3,Jakobe Erickson
2996,3423,28-Dec-20,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unk,Production,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3,Adyson Strickland
2997,3424,09-Dec-20,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Production,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2,Annabel Wilkins
2998,3425,28-May-19,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Production,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2,Kendra Braun
2999,3426,27-Apr-22,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unk,Production,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2,Chace Kerr

In [172]:
# moving full name to index 1, axis 1 i.e beside Employee OD
df = df.loc[:,[
'Employee ID', 'Full Name', 'Start Date' ,	'Title', 'Supervisor',
'Mail',	'Business Unit', 'Employee Status',	'Job Type',	'Zone',	'Contract Type',
'Termination Type',	'Department', 'Division', 'Date of Birth', 'State',	'Job',
'Gender', 'Zipcode','RaceDesc',	'Marital Status','Performance Score', 'Current Employee Rating'
]]

In [173]:
# Renaming the values in state column
df['State'].replace('AL', 'Alabama', inplace=True)
df['State'].replace('AZ', 'Arizona', inplace=True)
df['State'].replace('CA', 'California', inplace=True)
df['State'].replace('CO', 'Colorado', inplace=True)
df['State'].replace('CT', 'Connecticut', inplace=True)
df['State'].replace('FL', 'Florida', inplace=True)
df['State'].replace('GA', 'Georgia', inplace=True)
df['State'].replace('ID', 'Idaho', inplace=True)
df['State'].replace('IN', 'Indiana', inplace=True)
df['State'].replace('KY', 'Kentucky', inplace=True)
df['State'].replace('MA', 'Massachussets', inplace=True)
df['State'].replace('ME', 'Maine', inplace=True)
df['State'].replace('MT', 'Montana', inplace=True)
df['State'].replace('NC', 'North Carolina', inplace=True)
df['State'].replace('ND', 'North Dakota', inplace=True)
df['State'].replace('NH', 'New Hamphshire', inplace=True)
df['State'].replace('NV', 'Nevada', inplace=True)
df['State'].replace('NY', 'New York', inplace=True)
df['State'].replace('OH', 'Ohio', inplace=True)
df['State'].replace('OR', 'Oregon', inplace=True)
df['State'].replace('PA', 'Pennsylvania', inplace=True)
df['State'].replace('RI', 'Rhode Island', inplace=True)
df['State'].replace('TN', 'Tennesse', inplace=True)
df['State'].replace('TX', 'Texas', inplace=True)
df['State'].replace('UT', 'Utah', inplace=True)
df['State'].replace('VA', 'Virginia', inplace=True)
df['State'].replace('VT', 'Vermont', inplace=True)
df['State'].replace('WA', 'Washington', inplace=True)

In [174]:
df['Termination Type'].replace('Unk', 'Unknown', inplace=True)
df['Department'].replace('IT/IS', 'IT', inplace=True)
df['Division'].replace('Technology / It', 'Technology', inplace=True)
df['Division'].replace('Catv', 'Cable Television', inplace=True)
df['Division'].replace('Corp Operations', 'Cooperate ', inplace=True)
df['Division'].replace('General - Sga', 'General - Selling General and Administrative', inplace=True)
df['Division'].replace('General - Con', ' General - Conference', inplace=True)
df['Division'].replace('General - Eng', 'General - Engineering', inplace=True)
df['Division'].replace('Isp', 'Internet Service Provider', inplace=True)
df['Job'].replace('Cfo', 'Chief Financial Officer', inplace=True)
df['Job'].replace('Cio', 'Chief Informaion Officer', inplace=True)
df['Job'].replace('Cpo', 'Chief Product Officer', inplace=True)
df['Job'].replace('Evp', 'Executive Vice President', inplace=True)
df['Job'].replace('Svp', 'Senior Vice President', inplace=True)
df['Job'].replace('Vp', 'Vice President', inplace=True)
df['Job'].replace('Ceo', 'Chief Financial Officer', inplace=True)

In [175]:
df

,Employee ID,Full Name,Start Date,Title,Supervisor,Mail,Business Unit,Employee Status,Job Type,Zone,Contract Type,Termination Type,Department,Division,Date of Birth,State,Job,Gender,Zipcode,RaceDesc,Marital Status,Performance Score,Current Employee Rating
0,3427,Uriah Bridges,20-Sep-19,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unknown,Production,Finance & Accounting,07-10-1969,Massachussets,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula Small,11-Feb-23,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unknown,Production,Aerial,30-08-1965,Massachussets,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward Buck,10-Dec-18,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unknown,Sales,General - Selling General and Administrative,06-10-1991,Massachussets,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael Riordan,21-Jun-21,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unknown,Sales,Finance & Accounting,04-04-1998,North Dakota,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine Onque,29-Jun-19,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unknown,Sales,General - Conference,29-08-1969,Florida,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe Erickson,22-Jun-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,Production,Engineers,23-06-1998,Massachussets,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson Strickland,28-Dec-20,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unknown,Production,Engineers,10-06-2001,Massachussets,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel Wilkins,09-Dec-20,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Production,Wireline Construction,27-01-1997,Massachussets,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra Braun,28-May-19,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Production,Aerial,28-05-1954,Massachussets,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace Kerr,27-Apr-22,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unknown,Production,Field Operations,11-09-1990,Massachussets,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [176]:
# dropping duplicates
df.drop_duplicates()

,Employee ID,Full Name,Start Date,Title,Supervisor,Mail,Business Unit,Employee Status,Job Type,Zone,Contract Type,Termination Type,Department,Division,Date of Birth,State,Job,Gender,Zipcode,RaceDesc,Marital Status,Performance Score,Current Employee Rating
0,3427,Uriah Bridges,20-Sep-19,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unknown,Production,Finance & Accounting,07-10-1969,Massachussets,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula Small,11-Feb-23,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unknown,Production,Aerial,30-08-1965,Massachussets,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward Buck,10-Dec-18,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unknown,Sales,General - Selling General and Administrative,06-10-1991,Massachussets,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael Riordan,21-Jun-21,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unknown,Sales,Finance & Accounting,04-04-1998,North Dakota,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine Onque,29-Jun-19,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unknown,Sales,General - Conference,29-08-1969,Florida,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe Erickson,22-Jun-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,Production,Engineers,23-06-1998,Massachussets,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson Strickland,28-Dec-20,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unknown,Production,Engineers,10-06-2001,Massachussets,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel Wilkins,09-Dec-20,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Production,Wireline Construction,27-01-1997,Massachussets,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra Braun,28-May-19,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Production,Aerial,28-05-1954,Massachussets,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace Kerr,27-Apr-22,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unknown,Production,Field Operations,11-09-1990,Massachussets,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [177]:
# dropping null values
df.dropna()

,Employee ID,Full Name,Start Date,Title,Supervisor,Mail,Business Unit,Employee Status,Job Type,Zone,Contract Type,Termination Type,Department,Division,Date of Birth,State,Job,Gender,Zipcode,RaceDesc,Marital Status,Performance Score,Current Employee Rating
0,3427,Uriah Bridges,20-Sep-19,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,Zone C,Temporary,Unknown,Production,Finance & Accounting,07-10-1969,Massachussets,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula Small,11-Feb-23,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,Zone A,Part-Time,Unknown,Production,Aerial,30-08-1965,Massachussets,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward Buck,10-Dec-18,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,Zone B,Part-Time,Unknown,Sales,General - Selling General and Administrative,06-10-1991,Massachussets,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael Riordan,21-Jun-21,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,Zone A,Full-Time,Unknown,Sales,Finance & Accounting,04-04-1998,North Dakota,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine Onque,29-Jun-19,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,Zone A,Temporary,Unknown,Sales,General - Conference,29-08-1969,Florida,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe Erickson,22-Jun-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,Zone C,Part-Time,Retirement,Production,Engineers,23-06-1998,Massachussets,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson Strickland,28-Dec-20,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,Zone A,Full-Time,Unknown,Production,Engineers,10-06-2001,Massachussets,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel Wilkins,09-Dec-20,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,Zone B,Temporary,Involuntary,Production,Wireline Construction,27-01-1997,Massachussets,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra Braun,28-May-19,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,Zone B,Full-Time,Resignation,Production,Aerial,28-05-1954,Massachussets,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace Kerr,27-Apr-22,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,Zone B,Temporary,Unknown,Production,Field Operations,11-09-1990,Massachussets,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [178]:
# exporting into a new csv file
df.to_csv(r"C:\Users\Apex PC\Downloads\HR Employee\employee_data_cleaned.csv")